from __future__ import annotations

import hashlib
import json
from collections.abc import Callable, Mapping, Sequence
from typing import Any

from autoagent.ai.models.llm import (
    LLMMessage,
    LLMRequest,
    LLMResponse,
)
from autoagent.ai.models.user_event import (
    AgentOutputPayload,
    ToolResultPayload,
)
from autoagent.ai.nodes import llm_call_node
from autoagent.ai.models.react import (
    ConversationUpdate,
    OutputValidationResult,
    PreparedLLMCall,
    ToolCallBatch,
    ToolExecutionBatch,
    ToolExecutionResult,
)
from autoagent.ai.tools import ToolDefinition, get_tool_definition
from autoagent.ai.workflows.react.conversation import (
    ConversationPlan,
    initial_messages_from_value,
)
from autoagent.ai.workflows.react.output_validation import (
    OutputValidator,
    StructuredOutputRepairExhausted,
)
from autoagent.ai.workflows.react.tool_execution import (
    ToolArgumentsRepairExhausted,
    ToolExecutionPlan,
    recoverable_tool_handler,
    validate_tools,
)
from autoagent.core.operators import Operator
from autoagent.core.workflow import (
    MapPolicy,
    NodePolicy,
    RecoveryPolicy,
    ResourcePolicy,
    Workflow,
    UserEventMapping,
)


def react_workflow(
    *,
    id: str,
    instructions: str,
    tools: Sequence[Callable[..., Any]] = (),
    response_format: Any | None = None,
    model: str | None = None,
    max_steps: int = 20,
    max_tool_parse_retries: int = 1,
    max_output_parse_retries: int = 1,
    name: str | None = None,
    description: str | None = None,
) -> Workflow:
    """Build a single-entry/single-exit ReAct child Workflow.

    Parse retry counts mean additional LLM calls after the first invalid model
    response. They are separate from transport-level Node retry policies.
    """

    if not id.strip():
        raise ValueError("ReAct Workflow id cannot be empty.")
    if not instructions.strip():
        raise ValueError("ReAct Workflow instructions cannot be empty.")
    if max_steps < 1:
        raise ValueError("max_steps must be at least 1.")
    if max_tool_parse_retries < 0 or max_output_parse_retries < 0:
        raise ValueError("Parse retry counts cannot be negative.")

    definitions = tuple(get_tool_definition(item) for item in tools)
    validate_tools(definitions)
    llm_tools = tuple(item.llm_definition() for item in definitions)
    conversation = ConversationPlan(
        instructions=instructions,
        model=model,
        tools=llm_tools,
        response_format=response_format,
    )
    tool_execution = ToolExecutionPlan(
        definitions=definitions,
        max_parse_retries=max_tool_parse_retries,
    )
    output_validator = OutputValidator(
        response_format=response_format,
        max_parse_retries=max_output_parse_retries,
    )
    semantic_version = _semantic_version(
        {
            "instructions": instructions,
            "tools": [item.model_dump(mode="json") for item in llm_tools],
            "response_format": (
                LLMRequest(messages=(), response_format=response_format)
                .model_dump(mode="json")["response_format"]
                if response_format is not None
                else None
            ),
            "model": model,
            "max_steps": max_steps,
            "max_tool_parse_retries": max_tool_parse_retries,
            "max_output_parse_retries": max_output_parse_retries,
        }
    )

    workflow = Workflow(
        id=id,
        name=name or id,
        description=description or "ReAct Workflow generated by AutoAgent.",
    )

    def map_start(ctx: Any) -> dict[str, Any]:
        source = (
            ctx.incoming[0].value
            if ctx.incoming
            else ctx.invocation_input
        )
        source_options = source if isinstance(source, Mapping) else {}
        source_request = source if isinstance(source, LLMRequest) else None
        return {
            "initial_messages": initial_messages_from_value(source),
            "history_messages": _session_messages(
                ctx.session_context.data,
                ctx.workflow_path,
            ),
            "provider_options": (
                source_request.provider_options
                if source_request is not None
                else source_options.get("provider_options")
            ),
            "mode": source_options.get("mode", "invoke"),
        }

    def bind_initial_messages(ctx: Any) -> None:
        update = ctx.output
        if not isinstance(update, ConversationUpdate):
            raise TypeError("start must produce ConversationUpdate.")
        _append_session_messages(
            ctx.session_context.data,
            ctx.workflow_path,
            update.messages,
        )

    def bind_tool_messages(ctx: Any) -> None:
        update = ctx.output
        if not isinstance(update, ConversationUpdate):
            raise TypeError("collect_tool_results must produce ConversationUpdate.")
        _append_session_messages(
            ctx.session_context.data,
            ctx.workflow_path,
            update.messages,
        )

    def bind_final_message(ctx: Any) -> None:
        result = ctx.outputs.latest("validate_output")
        if not isinstance(result, OutputValidationResult) or not result.valid:
            raise TypeError("finish requires a valid OutputValidationResult.")
        _append_session_messages(
            ctx.session_context.data,
            ctx.workflow_path,
            (result.response.message,),
        )

    def map_prepare(ctx: Any) -> dict[str, Any]:
        return {
            "previous": ctx.outputs.latest("prepare_conversation", None),
            "update": ctx.incoming[0].value,
        }

    def map_incoming(ctx: Any) -> dict[str, Any]:
        call = ctx.incoming[0].value
        if not isinstance(call, PreparedLLMCall):
            raise TypeError("prepare_conversation must produce PreparedLLMCall.")
        return {"request": call.request, "mode": call.mode}

    def classify_response(response: LLMResponse) -> LLMResponse:
        return response

    def tool_results(batch: ToolExecutionBatch) -> dict[str, Any]:
        return ToolResultPayload(
            results=batch.results,
        ).model_dump(mode="json")

    def agent_output(value: Any) -> dict[str, Any]:
        return AgentOutputPayload(output=value).model_dump(mode="json")

    def map_response(ctx: Any) -> dict[str, Any]:
        return {"response": ctx.incoming[0].value}

    def map_tool_validation(ctx: Any) -> dict[str, Any]:
        previous = sum(
            1
            for item in ctx.outputs.all("validate_tool_calls")
            if item.invalid_calls
        )
        return {
            "response": ctx.incoming[0].value,
            "previous_failures": previous,
        }

    def map_collect(ctx: Any) -> dict[str, Any]:
        batch = ctx.outputs.latest("validate_tool_calls")
        executions: list[ToolExecutionResult] = []
        for incoming in ctx.incoming:
            if isinstance(incoming.value, ToolExecutionBatch):
                executions.extend(incoming.value.results)
        return {"batch": batch, "executions": tuple(executions)}

    def map_output_validation(ctx: Any) -> dict[str, Any]:
        previous = sum(
            1
            for item in ctx.outputs.all("validate_output")
            if not item.valid
        )
        return {
            "response": ctx.incoming[0].value,
            "previous_failures": previous,
        }

    def map_validation_result(ctx: Any) -> dict[str, Any]:
        return {"result": ctx.incoming[0].value}

    workflow.add_node(
        _internal_operator(id, "start", semantic_version, conversation.start),
        node_id="start",
        entry=True,
        input_mapping=map_start,
        output_binding=bind_initial_messages,
    )
    workflow.add_node(
        _internal_operator(
            id, "prepare_conversation", semantic_version, conversation.prepare
        ),
        node_id="prepare_conversation",
        input_mapping=map_prepare,
        policy=NodePolicy(
            resource=ResourcePolicy(
                max_node_executions_per_invocation=max_steps,
            )
        ),
    )
    workflow.add_node(
        llm_call_node(
            id="llm_call",
            input_mapping=map_incoming,
            policy=NodePolicy(
                recovery=RecoveryPolicy(mode="never"),
                resource=ResourcePolicy(
                    max_node_executions_per_invocation=max_steps,
                ),
            ),
        ),
    )
    workflow.add_node(
        _internal_operator(
            id, "classify_response", semantic_version, classify_response
        ),
        node_id="classify_response",
        input_mapping=map_response,
    )
    workflow.add_node(
        _internal_operator(
            id,
            "validate_tool_calls",
            semantic_version,
            tool_execution.validate_calls,
        ),
        node_id="validate_tool_calls",
        input_mapping=map_tool_validation,
    )
    workflow.add_node(
        _internal_operator(
            id,
            "collect_tool_results",
            semantic_version,
            tool_execution.collect_results,
        ),
        node_id="collect_tool_results",
        input_mapping=map_collect,
        output_binding=bind_tool_messages,
    )
    workflow.add_node(
        _internal_operator(
            id,
            "validate_output",
            semantic_version,
            output_validator.validate,
        ),
        node_id="validate_output",
        input_mapping=map_output_validation,
    )
    workflow.add_node(
        _internal_operator(
            id,
            "build_output_repair",
            semantic_version,
            conversation.build_output_repair,
        ),
        node_id="build_output_repair",
        input_mapping=map_validation_result,
    )
    workflow.add_node(
        _internal_operator(id, "finish", semantic_version, output_validator.finish),
        node_id="finish",
        input_mapping=map_validation_result,
        output_binding=bind_final_message,
        user_event_mapping=UserEventMapping(
            type="agent_output",
            transform=agent_output,
        ),
    )

    workflow.add_edge("start", "prepare_conversation", edge_id="start_prepare")
    workflow.add_edge("prepare_conversation", "llm_call", edge_id="prepare_llm")
    workflow.add_edge("llm_call", "classify_response", edge_id="llm_classify")
    workflow.add_edge(
        "classify_response",
        "validate_tool_calls",
        edge_id="classify_tools",
        condition=lambda ctx: bool(ctx.source_output.message.tool_calls),
    )
    workflow.add_edge(
        "classify_response",
        "validate_output",
        edge_id="classify_output",
        condition=lambda ctx: not ctx.source_output.message.tool_calls,
    )

    for index, (handler, definition) in enumerate(zip(tools, definitions, strict=True)):
        node_id = f"tool_{index}_{_node_token(definition.name)}"

        def select_calls(
            ctx: Any,
            *,
            selected_name: str = definition.name,
        ) -> list[Mapping[str, Any]]:
            return [
                {"arguments": item.arguments}
                for item in ctx.input.valid_calls
                if item.call.name == selected_name
            ]

        def aggregate_calls(
            ctx: Any,
            *,
            selected_name: str = definition.name,
            selected_id: str = definition.id,
        ) -> ToolExecutionBatch:
            batch = ctx.outputs.latest("validate_tool_calls")
            selected = [
                item
                for item in batch.valid_calls
                if item.call.name == selected_name
            ]
            return ToolExecutionBatch(
                results=tuple(
                    ToolExecutionResult(
                        call_index=item.call_index,
                        tool_call_id=item.call.id,
                        tool_id=selected_id,
                        output=output.output,
                        error=output.error,
                    )
                    for item, output in zip(
                        selected,
                        ctx.item_outputs,
                        strict=True,
                    )
                )
            )

        recoverable_handler = recoverable_tool_handler(handler)
        setattr(
            recoverable_handler,
            "__autoagent_runtime_annotations__",
            (
                definition.contract.output.annotation,
                *(
                    parameter.annotation
                    for parameter in definition.contract.input.parameters
                ),
            ),
        )
        workflow.add_node(
            Operator(
                id=definition.id,
                handler=recoverable_handler,
                version=semantic_version,
            ),
            node_id=node_id,
            user_event_mapping=UserEventMapping(
                type="tool_result",
                transform=tool_results,
            ),
            policy=NodePolicy(
                map=MapPolicy(
                    item_selector=select_calls,
                    output_aggregator=aggregate_calls,
                )
            ),
        )
        workflow.add_edge(
            "validate_tool_calls",
            node_id,
            edge_id=f"validated_{node_id}",
            condition=(
                lambda ctx, selected_name=definition.name: any(
                    item.call.name == selected_name
                    for item in ctx.source_output.valid_calls
                )
            ),
        )
        workflow.add_edge(
            node_id,
            "collect_tool_results",
            edge_id=f"{node_id}_collect",
        )

    workflow.add_edge(
        "validate_tool_calls",
        "collect_tool_results",
        edge_id="invalid_tools_collect",
        condition=lambda ctx: not ctx.source_output.valid_calls,
    )
    workflow.add_edge(
        "collect_tool_results",
        "prepare_conversation",
        edge_id="tools_prepare",
    )
    workflow.add_edge(
        "validate_output",
        "finish",
        edge_id="output_finish",
        condition=lambda ctx: ctx.source_output.valid,
    )
    workflow.add_edge(
        "validate_output",
        "build_output_repair",
        edge_id="output_repair",
        condition=lambda ctx: not ctx.source_output.valid,
    )
    workflow.add_edge(
        "build_output_repair",
        "prepare_conversation",
        edge_id="repair_prepare",
    )
    return workflow


def _internal_operator(
    workflow_id: str,
    name: str,
    version: str,
    handler: Callable[..., Any],
) -> Operator:
    return Operator(
        id=f"{workflow_id}.__react__.{name}",
        handler=handler,
        version=version,
    )


def _semantic_version(value: Any) -> str:
    payload = json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(payload).hexdigest()[:16]


def _node_token(value: str) -> str:
    return "".join(character if character.isalnum() else "_" for character in value)


_REACT_SESSION_MESSAGES_KEY = "__autoagent_react_messages__"
_ROOT_WORKFLOW_PATH = "$"


def _session_messages(
    session_data: Mapping[str, Any],
    workflow_path: tuple[str, ...],
) -> tuple[LLMMessage, ...]:
    histories = session_data.get(_REACT_SESSION_MESSAGES_KEY, {})
    if not isinstance(histories, Mapping):
        raise TypeError(
            f"Session Context {_REACT_SESSION_MESSAGES_KEY!r} must be a mapping."
        )
    raw_messages = histories.get(_workflow_path_key(workflow_path), ())
    if not isinstance(raw_messages, (list, tuple)):
        raise TypeError("ReAct Session messages must be a list.")
    return tuple(
        item if isinstance(item, LLMMessage) else LLMMessage.model_validate(item)
        for item in raw_messages
    )


def _append_session_messages(
    session_data: dict[str, Any],
    workflow_path: tuple[str, ...],
    messages: tuple[LLMMessage, ...],
) -> None:
    histories = session_data.setdefault(_REACT_SESSION_MESSAGES_KEY, {})
    if not isinstance(histories, dict):
        raise TypeError(
            f"Session Context {_REACT_SESSION_MESSAGES_KEY!r} must be a mapping."
        )
    history = histories.setdefault(_workflow_path_key(workflow_path), [])
    if not isinstance(history, list):
        raise TypeError("ReAct Session messages must be a list.")
    history.extend(messages)


def _workflow_path_key(workflow_path: tuple[str, ...]) -> str:
    return "/".join(workflow_path) if workflow_path else _ROOT_WORKFLOW_PATH
