from __future__ import annotations

import hashlib
import inspect
import json
from collections.abc import Callable, Mapping, Sequence
from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, TypeAdapter, ValidationError

from autoagent.ai.llm import (
    LLM_CALL_CAPABILITY_ID,
    LLMMessage,
    LLMRequest,
    LLMResponse,
    LLMToolCall,
)
from autoagent.ai.tool import ToolDefinition, get_tool_definition
from autoagent.core.operators import Operator
from autoagent.core.workflow import (
    CapabilityRef,
    EdgePolicy,
    MapPolicy,
    NodePolicy,
    RecoveryPolicy,
    ResourcePolicy,
    Workflow,
)


class ToolArgumentsRepairExhausted(ValueError):
    pass


class StructuredOutputRepairExhausted(ValueError):
    pass


class ConversationUpdate(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    kind: Literal["initial", "tool_results", "output_repair"]
    messages: tuple[LLMMessage, ...]


class ParsedToolCall(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    call: LLMToolCall
    tool_id: str
    arguments: dict[str, Any]


class InvalidToolCall(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    call: LLMToolCall
    error: str


class ToolCallBatch(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    response: LLMResponse
    valid_calls: tuple[ParsedToolCall, ...] = ()
    invalid_calls: tuple[InvalidToolCall, ...] = ()


class ToolExecutionError(BaseModel):
    model_config = ConfigDict(extra="forbid", frozen=True)

    type: str
    message: str


class ToolExecutionResult(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True, extra="forbid", frozen=True)

    tool_call_id: str
    tool_id: str
    output: Any = None
    error: ToolExecutionError | None = None


class _ToolInvocationOutcome(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True, extra="forbid", frozen=True)

    output: Any = None
    error: ToolExecutionError | None = None


class ToolExecutionBatch(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True, extra="forbid", frozen=True)

    results: tuple[ToolExecutionResult, ...]


class OutputValidationResult(BaseModel):
    model_config = ConfigDict(arbitrary_types_allowed=True, extra="forbid", frozen=True)

    response: LLMResponse
    valid: bool
    value: Any = None
    error: str | None = None


def react_workflow(
    *,
    id: str,
    instructions: str,
    tools: Sequence[Callable[..., Any]] = (),
    response_format: Any | None = None,
    model: str | None = None,
    max_steps: int = 20,
    max_tool_parse_retries: int = 1,
    max_output_parse_retries: int = 1,
    name: str | None = None,
    description: str | None = None,
) -> Workflow:
    """Build a single-entry/single-exit ReAct child Workflow.

    Parse retry counts mean additional LLM calls after the first invalid model
    response. They are separate from transport-level Node retry policies.
    """

    if not id.strip():
        raise ValueError("ReAct Workflow id cannot be empty.")
    if not instructions.strip():
        raise ValueError("ReAct Workflow instructions cannot be empty.")
    if max_steps < 1:
        raise ValueError("max_steps must be at least 1.")
    if max_tool_parse_retries < 0 or max_output_parse_retries < 0:
        raise ValueError("Parse retry counts cannot be negative.")

    definitions = tuple(get_tool_definition(item) for item in tools)
    _validate_tools(definitions)
    llm_tools = tuple(item.llm_definition() for item in definitions)
    semantic_version = _semantic_version(
        {
            "instructions": instructions,
            "tools": [item.model_dump(mode="json") for item in llm_tools],
            "response_format": (
                LLMRequest(messages=(), response_format=response_format)
                .model_dump(mode="json")["response_format"]
                if response_format is not None
                else None
            ),
            "model": model,
            "max_steps": max_steps,
            "max_tool_parse_retries": max_tool_parse_retries,
            "max_output_parse_retries": max_output_parse_retries,
        }
    )

    workflow = Workflow(
        id=id,
        name=name or id,
        description=description or "ReAct Workflow generated by AutoAgent.",
    )

    def start(initial_messages: tuple[LLMMessage, ...]) -> ConversationUpdate:
        return ConversationUpdate(kind="initial", messages=initial_messages)

    def map_start(ctx: Any) -> dict[str, Any]:
        source = (
            ctx.incoming[0].value
            if ctx.incoming
            else ctx.invocation_input
        )
        if isinstance(source, str):
            raw_messages: Any = [LLMMessage(role="user", content=source)]
        elif isinstance(source, LLMMessage):
            raw_messages = [source]
        elif isinstance(source, Mapping):
            raw_messages = source.get("messages")
            if raw_messages is None and "input" in source:
                raw_messages = [
                    LLMMessage(role="user", content=str(source["input"]))
                ]
            if raw_messages is None:
                raise ValueError(
                    "ReAct Workflow input requires 'input' or 'messages'."
                )
        else:
            raw_messages = source
        return {
            "initial_messages": tuple(
                item if isinstance(item, LLMMessage) else LLMMessage.model_validate(item)
                for item in raw_messages
            )
        }

    def prepare_conversation(
        previous: LLMRequest | None,
        update: ConversationUpdate,
    ) -> LLMRequest:
        messages = list(previous.messages if previous is not None else ())
        if previous is None:
            messages.append(LLMMessage(role="system", content=instructions))
        messages.extend(update.messages)
        return LLMRequest(
            messages=tuple(messages),
            model=model,
            tools=llm_tools,
            tool_choice=(
                "none"
                if update.kind == "output_repair" or not llm_tools
                else "auto"
            ),
            response_format=response_format,
        )

    def map_prepare(ctx: Any) -> dict[str, Any]:
        return {
            "previous": ctx.outputs.latest("prepare_conversation", None),
            "update": ctx.incoming[0].value,
        }

    def map_incoming(ctx: Any) -> dict[str, Any]:
        return {"request": ctx.incoming[0].value}

    def classify_response(response: LLMResponse) -> LLMResponse:
        return response

    def map_response(ctx: Any) -> dict[str, Any]:
        return {"response": ctx.incoming[0].value}

    tool_by_name = {item.name: item for item in definitions}

    def validate_tool_calls(
        response: LLMResponse,
        previous_failures: int,
    ) -> ToolCallBatch:
        valid: list[ParsedToolCall] = []
        invalid: list[InvalidToolCall] = []
        for call in response.message.tool_calls:
            definition = tool_by_name.get(call.name)
            if definition is None:
                invalid.append(
                    InvalidToolCall(call=call, error=f"Unknown tool: {call.name}")
                )
                continue
            try:
                decoded = json.loads(call.raw_arguments)
                arguments = definition.contract.input.validate(decoded)
            except Exception as exc:
                invalid.append(InvalidToolCall(call=call, error=str(exc)))
                continue
            valid.append(
                ParsedToolCall(
                    call=call,
                    tool_id=definition.id,
                    arguments=arguments,
                )
            )
        if invalid and previous_failures >= max_tool_parse_retries:
            raise ToolArgumentsRepairExhausted(
                "Tool arguments remained invalid after "
                f"{max_tool_parse_retries} repair attempt(s): "
                + "; ".join(item.error for item in invalid)
            )
        return ToolCallBatch(
            response=response,
            valid_calls=tuple(valid),
            invalid_calls=tuple(invalid),
        )

    def map_tool_validation(ctx: Any) -> dict[str, Any]:
        previous = sum(
            1
            for item in ctx.outputs.all("validate_tool_calls")
            if item.invalid_calls
        )
        return {
            "response": ctx.incoming[0].value,
            "previous_failures": previous,
        }

    def collect_tool_results(
        batch: ToolCallBatch,
        executions: tuple[ToolExecutionResult, ...],
    ) -> ConversationUpdate:
        results = {item.tool_call_id: item for item in executions}
        invalid = {item.call.id: item for item in batch.invalid_calls}
        messages: list[LLMMessage] = [batch.response.message]
        for call in batch.response.message.tool_calls:
            failed = invalid.get(call.id)
            if failed is not None:
                content = json.dumps(
                    {
                        "error": {
                            "type": "tool_arguments_validation_error",
                            "tool": call.name,
                            "message": failed.error,
                            "raw_arguments": call.raw_arguments,
                        }
                    },
                    separators=(",", ":"),
                )
            else:
                executed = results[call.id]
                if executed.error is None:
                    content = _tool_output_json(executed.output)
                else:
                    content = json.dumps(
                        {
                            "error": {
                                "type": "tool_execution_error",
                                "tool": call.name,
                                "exception_type": executed.error.type,
                                "message": executed.error.message,
                            }
                        },
                        separators=(",", ":"),
                    )
            messages.append(
                LLMMessage(
                    role="tool",
                    name=call.name,
                    tool_call_id=call.id,
                    content=content,
                )
            )
        return ConversationUpdate(kind="tool_results", messages=tuple(messages))

    def map_collect(ctx: Any) -> dict[str, Any]:
        batch = ctx.outputs.latest("validate_tool_calls")
        executions: list[ToolExecutionResult] = []
        for incoming in ctx.incoming:
            if isinstance(incoming.value, ToolExecutionBatch):
                executions.extend(incoming.value.results)
        return {"batch": batch, "executions": tuple(executions)}

    def validate_output(
        response: LLMResponse,
        previous_failures: int,
    ) -> OutputValidationResult:
        content = response.message.content
        if response_format is None:
            return OutputValidationResult(
                response=response,
                valid=True,
                value=content,
            )
        try:
            if content is None:
                raise ValueError("Structured response content is missing.")
            adapter = TypeAdapter(response_format)
            value = adapter.validate_json(content)
            normalized = adapter.dump_python(value, mode="json")
            return OutputValidationResult(
                response=response,
                valid=True,
                value=normalized,
            )
        except (ValidationError, ValueError, TypeError) as exc:
            if previous_failures >= max_output_parse_retries:
                raise StructuredOutputRepairExhausted(
                    "Structured output remained invalid after "
                    f"{max_output_parse_retries} repair attempt(s): {exc}"
                ) from exc
            return OutputValidationResult(
                response=response,
                valid=False,
                error=str(exc),
            )

    def map_output_validation(ctx: Any) -> dict[str, Any]:
        previous = sum(
            1
            for item in ctx.outputs.all("validate_output")
            if not item.valid
        )
        return {
            "response": ctx.incoming[0].value,
            "previous_failures": previous,
        }

    def build_output_repair(
        result: OutputValidationResult,
    ) -> ConversationUpdate:
        return ConversationUpdate(
            kind="output_repair",
            messages=(
                result.response.message,
                LLMMessage(
                    role="user",
                    content=(
                        "Your previous response did not match the required output "
                        "schema. Return only a corrected structured response. "
                        f"Validation error: {result.error}"
                    ),
                ),
            ),
        )

    def map_validation_result(ctx: Any) -> dict[str, Any]:
        return {"result": ctx.incoming[0].value}

    def finish(result: OutputValidationResult) -> Any:
        return result.value

    workflow.add_node(
        _internal_operator(id, "start", semantic_version, start),
        node_id="start",
        entry=True,
        input_mapping=map_start,
    )
    workflow.add_node(
        _internal_operator(
            id, "prepare_conversation", semantic_version, prepare_conversation
        ),
        node_id="prepare_conversation",
        input_mapping=map_prepare,
        policy=NodePolicy(
            resource=ResourcePolicy(
                max_node_executions_per_invocation=max_steps,
            )
        ),
    )
    workflow.add_node(
        CapabilityRef(id=LLM_CALL_CAPABILITY_ID),
        node_id="llm_call",
        input_mapping=map_incoming,
        policy=NodePolicy(
            recovery=RecoveryPolicy(mode="never"),
            resource=ResourcePolicy(
                max_node_executions_per_invocation=max_steps,
            ),
        ),
    )
    workflow.add_node(
        _internal_operator(
            id, "classify_response", semantic_version, classify_response
        ),
        node_id="classify_response",
        input_mapping=map_response,
    )
    workflow.add_node(
        _internal_operator(
            id, "validate_tool_calls", semantic_version, validate_tool_calls
        ),
        node_id="validate_tool_calls",
        input_mapping=map_tool_validation,
    )
    workflow.add_node(
        _internal_operator(
            id, "collect_tool_results", semantic_version, collect_tool_results
        ),
        node_id="collect_tool_results",
        input_mapping=map_collect,
    )
    workflow.add_node(
        _internal_operator(id, "validate_output", semantic_version, validate_output),
        node_id="validate_output",
        input_mapping=map_output_validation,
    )
    workflow.add_node(
        _internal_operator(
            id, "build_output_repair", semantic_version, build_output_repair
        ),
        node_id="build_output_repair",
        input_mapping=map_validation_result,
    )
    workflow.add_node(
        _internal_operator(id, "finish", semantic_version, finish),
        node_id="finish",
        input_mapping=map_validation_result,
    )

    workflow.add_edge("start", "prepare_conversation", edge_id="start_prepare")
    workflow.add_edge("prepare_conversation", "llm_call", edge_id="prepare_llm")
    workflow.add_edge("llm_call", "classify_response", edge_id="llm_classify")
    workflow.add_edge(
        "classify_response",
        "validate_tool_calls",
        edge_id="classify_tools",
        condition=lambda ctx: bool(ctx.source_output.message.tool_calls),
    )
    workflow.add_edge(
        "classify_response",
        "validate_output",
        edge_id="classify_output",
        condition=lambda ctx: not ctx.source_output.message.tool_calls,
    )

    for index, (handler, definition) in enumerate(zip(tools, definitions, strict=True)):
        node_id = f"tool_{index}_{_node_token(definition.name)}"

        def select_calls(
            ctx: Any,
            *,
            selected_name: str = definition.name,
        ) -> list[Mapping[str, Any]]:
            return [
                {"arguments": item.arguments}
                for item in ctx.input.valid_calls
                if item.call.name == selected_name
            ]

        def aggregate_calls(
            ctx: Any,
            *,
            selected_name: str = definition.name,
            selected_id: str = definition.id,
        ) -> ToolExecutionBatch:
            batch = ctx.outputs.latest("validate_tool_calls")
            selected = [
                item
                for item in batch.valid_calls
                if item.call.name == selected_name
            ]
            return ToolExecutionBatch(
                results=tuple(
                    ToolExecutionResult(
                        tool_call_id=item.call.id,
                        tool_id=selected_id,
                        output=output.output,
                        error=output.error,
                    )
                    for item, output in zip(
                        selected,
                        ctx.item_outputs,
                        strict=True,
                    )
                )
            )

        recoverable_handler = _recoverable_tool_handler(handler)
        setattr(
            recoverable_handler,
            "__autoagent_runtime_annotations__",
            (
                definition.contract.output.annotation,
                *(
                    parameter.annotation
                    for parameter in definition.contract.input.parameters
                ),
            ),
        )
        workflow.add_node(
            Operator(
                id=definition.id,
                handler=recoverable_handler,
                version=semantic_version,
            ),
            node_id=node_id,
        )
        workflow.add_edge(
            "validate_tool_calls",
            node_id,
            edge_id=f"validated_{node_id}",
            condition=(
                lambda ctx, selected_name=definition.name: any(
                    item.call.name == selected_name
                    for item in ctx.source_output.valid_calls
                )
            ),
            policy=EdgePolicy(
                map=MapPolicy(
                    item_selector=select_calls,
                    output_aggregator=aggregate_calls,
                )
            ),
        )
        workflow.add_edge(
            node_id,
            "collect_tool_results",
            edge_id=f"{node_id}_collect",
        )

    workflow.add_edge(
        "validate_tool_calls",
        "collect_tool_results",
        edge_id="invalid_tools_collect",
        condition=lambda ctx: not ctx.source_output.valid_calls,
    )
    workflow.add_edge(
        "collect_tool_results",
        "prepare_conversation",
        edge_id="tools_prepare",
    )
    workflow.add_edge(
        "validate_output",
        "finish",
        edge_id="output_finish",
        condition=lambda ctx: ctx.source_output.valid,
    )
    workflow.add_edge(
        "validate_output",
        "build_output_repair",
        edge_id="output_repair",
        condition=lambda ctx: not ctx.source_output.valid,
    )
    workflow.add_edge(
        "build_output_repair",
        "prepare_conversation",
        edge_id="repair_prepare",
    )
    return workflow


def _recoverable_tool_handler(
    handler: Callable[..., Any],
) -> Callable[[dict[str, Any]], _ToolInvocationOutcome]:
    """Turn user Tool exceptions into observations the LLM can repair."""

    if inspect.iscoroutinefunction(handler) or inspect.iscoroutinefunction(
        getattr(handler, "__call__", None)
    ):

        async def invoke(arguments: dict[str, Any]) -> _ToolInvocationOutcome:
            try:
                return _ToolInvocationOutcome(output=await handler(**arguments))
            except Exception as exc:
                return _ToolInvocationOutcome(
                    error=ToolExecutionError(
                        type=type(exc).__name__,
                        message=str(exc),
                    )
                )

        return invoke

    def invoke(arguments: dict[str, Any]) -> _ToolInvocationOutcome:
        try:
            return _ToolInvocationOutcome(output=handler(**arguments))
        except Exception as exc:
            return _ToolInvocationOutcome(
                error=ToolExecutionError(
                    type=type(exc).__name__,
                    message=str(exc),
                )
            )

    return invoke


def _validate_tools(definitions: tuple[ToolDefinition, ...]) -> None:
    ids = [item.id for item in definitions]
    names = [item.name for item in definitions]
    if len(ids) != len(set(ids)):
        raise ValueError("ReAct Tool ids must be unique.")
    if len(names) != len(set(names)):
        raise ValueError("ReAct Tool names must be unique.")


def _internal_operator(
    workflow_id: str,
    name: str,
    version: str,
    handler: Callable[..., Any],
) -> Operator:
    return Operator(
        id=f"{workflow_id}.__react__.{name}",
        handler=handler,
        version=version,
    )


def _semantic_version(value: Any) -> str:
    payload = json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(payload).hexdigest()[:16]


def _node_token(value: str) -> str:
    return "".join(character if character.isalnum() else "_" for character in value)


def _tool_output_json(value: Any) -> str:
    adapter = TypeAdapter(type(value))
    return adapter.dump_json(value).decode("utf-8")
