"""Stable authoring and invocation API for AutoAgent V2."""

from .core.app import (
    AppCheckpoint,
    AutoAgentApp,
    CheckpointLoadResult,
    InvocationRef,
    InvocationResult,
    InvocationStatus,
    InvocationStream,
    InvocationSubmission,
    InvocationUpdate,
    InvocationWait,
    StreamItem,
)
from .core.compiler import (
    CompileResult,
    Diagnostic,
    WorkflowCompiler,
    WorkflowDefinitionSnapshot,
)
from .core.context import ContextOperation, ContextPatch
from .core.errors import (
    AutoAgentError,
    RuntimeInfrastructureError,
    RuntimeTransitionError,
    WorkflowCompileError,
)
from .core.operators import Operator, StreamReducer, ValueContract, Wait
from .core.runtime import SessionCheckpoint, RuntimeErrorInfo, UserEvent
from .core.workflow import (
    AggregationContext,
    Capability,
    ConditionContext,
    Context,
    Edge,
    ErrorInfo,
    InputMappingContext,
    Map,
    Node,
    OutputBindingContext,
    Recovery,
    Stream,
    StreamContext,
    SubWorkflow,
    UserEventMapping,
    Workflow,
    workflow_hook,
)

__all__ = [
    "AggregationContext",
    "AppCheckpoint",
    "AutoAgentApp",
    "AutoAgentError",
    "Capability",
    "CheckpointLoadResult",
    "CompileResult",
    "ConditionContext",
    "Context",
    "ContextOperation",
    "ContextPatch",
    "Diagnostic",
    "Edge",
    "ErrorInfo",
    "InputMappingContext",
    "InvocationRef",
    "InvocationResult",
    "InvocationStatus",
    "InvocationStream",
    "InvocationSubmission",
    "InvocationUpdate",
    "InvocationWait",
    "StreamItem",
    "Map",
    "Node",
    "Operator",
    "OutputBindingContext",
    "Recovery",
    "SessionCheckpoint",
    "RuntimeErrorInfo",
    "RuntimeInfrastructureError",
    "RuntimeTransitionError",
    "Stream",
    "StreamContext",
    "StreamReducer",
    "SubWorkflow",
    "UserEvent",
    "UserEventMapping",
    "ValueContract",
    "Wait",
    "Workflow",
    "WorkflowCompileError",
    "WorkflowCompiler",
    "WorkflowDefinitionSnapshot",
    "workflow_hook",
]

from .core import RuntimeGraphCheckpoint, ChildHandle
__all__ += ["RuntimeGraphCheckpoint", "ChildHandle"]
