from __future__ import annotations

import hashlib
import json
from collections.abc import Callable, Mapping, Sequence
from typing import Any

from autoagent.ai.capabilities.llm_call import LLM_CALL_CAPABILITY_ID
from autoagent.ai.models.llm import (
    LLMMessage,
    LLMRequest,
    LLMResponse,
    LLMStreamChunk,
)
from autoagent.ai.models.react import (
    PreparedLLMCall,
    ToolCallBatch,
    ToolExecutionBatch,
    ToolExecutionResult,
)
from autoagent.ai.tools import ToolDefinition, get_tool_definition
from autoagent.ai.workflows.react.conversation import (
    ConversationPlan,
    initial_messages_from_value,
)
from autoagent.ai.workflows.react.output_validation import (
    OutputValidator,
    StructuredOutputRepairExhausted,
)
from autoagent.ai.workflows.react.tool_execution import (
    ToolArgumentsRepairExhausted,
    ToolExecutionPlan,
    recoverable_tool_handler,
    validate_tools,
)
from autoagent.core.operators import Operator
from autoagent.core.workflow import (
    CapabilityRef,
    EdgePolicy,
    MapPolicy,
    NodePolicy,
    RecoveryPolicy,
    ResourcePolicy,
    Workflow,
    UserEventMapping,
)


def react_workflow(
    *,
    id: str,
    instructions: str,
    tools: Sequence[Callable[..., Any]] = (),
    response_format: Any | None = None,
    model: str | None = None,
    max_steps: int = 20,
    max_tool_parse_retries: int = 1,
    max_output_parse_retries: int = 1,
    name: str | None = None,
    description: str | None = None,
) -> Workflow:
    """Build a single-entry/single-exit ReAct child Workflow.

    Parse retry counts mean additional LLM calls after the first invalid model
    response. They are separate from transport-level Node retry policies.
    """

    if not id.strip():
        raise ValueError("ReAct Workflow id cannot be empty.")
    if not instructions.strip():
        raise ValueError("ReAct Workflow instructions cannot be empty.")
    if max_steps < 1:
        raise ValueError("max_steps must be at least 1.")
    if max_tool_parse_retries < 0 or max_output_parse_retries < 0:
        raise ValueError("Parse retry counts cannot be negative.")

    definitions = tuple(get_tool_definition(item) for item in tools)
    validate_tools(definitions)
    llm_tools = tuple(item.llm_definition() for item in definitions)
    conversation = ConversationPlan(
        instructions=instructions,
        model=model,
        tools=llm_tools,
        response_format=response_format,
    )
    tool_execution = ToolExecutionPlan(
        definitions=definitions,
        max_parse_retries=max_tool_parse_retries,
    )
    output_validator = OutputValidator(
        response_format=response_format,
        max_parse_retries=max_output_parse_retries,
    )
    semantic_version = _semantic_version(
        {
            "instructions": instructions,
            "tools": [item.model_dump(mode="json") for item in llm_tools],
            "response_format": (
                LLMRequest(messages=(), response_format=response_format)
                .model_dump(mode="json")["response_format"]
                if response_format is not None
                else None
            ),
            "model": model,
            "max_steps": max_steps,
            "max_tool_parse_retries": max_tool_parse_retries,
            "max_output_parse_retries": max_output_parse_retries,
        }
    )

    workflow = Workflow(
        id=id,
        name=name or id,
        description=description or "ReAct Workflow generated by AutoAgent.",
    )

    def map_start(ctx: Any) -> dict[str, Any]:
        source = (
            ctx.incoming[0].value
            if ctx.incoming
            else ctx.invocation_input
        )
        source_options = source if isinstance(source, Mapping) else {}
        source_request = source if isinstance(source, LLMRequest) else None
        return {
            "initial_messages": initial_messages_from_value(source),
            "provider_options": (
                source_request.provider_options
                if source_request is not None
                else source_options.get("provider_options")
            ),
            "mode": source_options.get("mode", "invoke"),
        }

    def map_prepare(ctx: Any) -> dict[str, Any]:
        return {
            "previous": ctx.outputs.latest("prepare_conversation", None),
            "update": ctx.incoming[0].value,
        }

    def map_incoming(ctx: Any) -> dict[str, Any]:
        call = ctx.incoming[0].value
        if not isinstance(call, PreparedLLMCall):
            raise TypeError("prepare_conversation must produce PreparedLLMCall.")
        return {"request": call.request, "mode": call.mode}

    def classify_response(response: LLMResponse) -> LLMResponse:
        return response

    def text_delta(chunk: LLMStreamChunk) -> dict[str, Any] | None:
        if chunk.type != "text_delta":
            return None
        return {"delta": chunk.text_delta}

    def reasoning_delta(chunk: LLMStreamChunk) -> dict[str, Any] | None:
        if chunk.type != "reasoning_delta":
            return None
        return {"delta": chunk.reasoning_delta}

    def tool_call_delta(chunk: LLMStreamChunk) -> dict[str, Any] | None:
        if chunk.type != "tool_call_delta":
            return None
        return {
            "tool_call_index": chunk.tool_call_index,
            "tool_call_id": chunk.tool_call_id,
            "tool_name": chunk.tool_name,
            "arguments_delta": chunk.tool_arguments_delta,
        }

    def completed_message(response: LLMResponse) -> dict[str, Any]:
        return response.model_dump(mode="json")

    def requested_tool_calls(batch: ToolCallBatch) -> dict[str, Any] | None:
        if not batch.valid_calls:
            return None
        return {
            "calls": [
                {
                    "tool_call_id": item.call.id,
                    "tool_id": item.tool_id,
                    "name": item.call.name,
                    "arguments": item.arguments,
                }
                for item in batch.valid_calls
            ]
        }

    def rejected_tool_calls(batch: ToolCallBatch) -> dict[str, Any] | None:
        if not batch.invalid_calls:
            return None
        return {
            "calls": [
                {
                    "tool_call_id": item.call.id,
                    "name": item.call.name,
                    "raw_arguments": item.call.raw_arguments,
                    "error": item.error,
                }
                for item in batch.invalid_calls
            ]
        }

    def tool_results(batch: ToolExecutionBatch) -> dict[str, Any]:
        return batch.model_dump(mode="json")

    def agent_output(value: Any) -> dict[str, Any]:
        return {"output": value}

    def map_response(ctx: Any) -> dict[str, Any]:
        return {"response": ctx.incoming[0].value}

    def map_tool_validation(ctx: Any) -> dict[str, Any]:
        previous = sum(
            1
            for item in ctx.outputs.all("validate_tool_calls")
            if item.invalid_calls
        )
        return {
            "response": ctx.incoming[0].value,
            "previous_failures": previous,
        }

    def map_collect(ctx: Any) -> dict[str, Any]:
        batch = ctx.outputs.latest("validate_tool_calls")
        executions: list[ToolExecutionResult] = []
        for incoming in ctx.incoming:
            if isinstance(incoming.value, ToolExecutionBatch):
                executions.extend(incoming.value.results)
        return {"batch": batch, "executions": tuple(executions)}

    def map_output_validation(ctx: Any) -> dict[str, Any]:
        previous = sum(
            1
            for item in ctx.outputs.all("validate_output")
            if not item.valid
        )
        return {
            "response": ctx.incoming[0].value,
            "previous_failures": previous,
        }

    def map_validation_result(ctx: Any) -> dict[str, Any]:
        return {"result": ctx.incoming[0].value}

    workflow.add_node(
        _internal_operator(id, "start", semantic_version, conversation.start),
        node_id="start",
        entry=True,
        input_mapping=map_start,
    )
    workflow.add_node(
        _internal_operator(
            id, "prepare_conversation", semantic_version, conversation.prepare
        ),
        node_id="prepare_conversation",
        input_mapping=map_prepare,
        policy=NodePolicy(
            resource=ResourcePolicy(
                max_node_executions_per_invocation=max_steps,
            )
        ),
    )
    workflow.add_node(
        CapabilityRef(id=LLM_CALL_CAPABILITY_ID),
        node_id="llm_call",
        input_mapping=map_incoming,
        policy=NodePolicy(
            recovery=RecoveryPolicy(mode="never"),
            resource=ResourcePolicy(
                max_node_executions_per_invocation=max_steps,
            ),
        ),
        metadata={"_autoagent_user_event_stream": "message"},
        stream_user_event_mapping=(
            UserEventMapping(type="message_delta", transform=text_delta),
            UserEventMapping(
                type="reasoning_delta",
                transform=reasoning_delta,
            ),
            UserEventMapping(
                type="tool_call_delta",
                transform=tool_call_delta,
            ),
        ),
        user_event_mapping=UserEventMapping(
            type="message_completed",
            transform=completed_message,
        ),
    )
    workflow.add_node(
        _internal_operator(
            id, "classify_response", semantic_version, classify_response
        ),
        node_id="classify_response",
        input_mapping=map_response,
    )
    workflow.add_node(
        _internal_operator(
            id,
            "validate_tool_calls",
            semantic_version,
            tool_execution.validate_calls,
        ),
        node_id="validate_tool_calls",
        input_mapping=map_tool_validation,
        user_event_mapping=(
            UserEventMapping(
                type="tool_call_requested",
                transform=requested_tool_calls,
            ),
            UserEventMapping(
                type="tool_call_rejected",
                transform=rejected_tool_calls,
            ),
        ),
    )
    workflow.add_node(
        _internal_operator(
            id,
            "collect_tool_results",
            semantic_version,
            tool_execution.collect_results,
        ),
        node_id="collect_tool_results",
        input_mapping=map_collect,
    )
    workflow.add_node(
        _internal_operator(
            id,
            "validate_output",
            semantic_version,
            output_validator.validate,
        ),
        node_id="validate_output",
        input_mapping=map_output_validation,
    )
    workflow.add_node(
        _internal_operator(
            id,
            "build_output_repair",
            semantic_version,
            conversation.build_output_repair,
        ),
        node_id="build_output_repair",
        input_mapping=map_validation_result,
    )
    workflow.add_node(
        _internal_operator(id, "finish", semantic_version, output_validator.finish),
        node_id="finish",
        input_mapping=map_validation_result,
        user_event_mapping=UserEventMapping(
            type="agent_output",
            transform=agent_output,
        ),
    )

    workflow.add_edge("start", "prepare_conversation", edge_id="start_prepare")
    workflow.add_edge("prepare_conversation", "llm_call", edge_id="prepare_llm")
    workflow.add_edge("llm_call", "classify_response", edge_id="llm_classify")
    workflow.add_edge(
        "classify_response",
        "validate_tool_calls",
        edge_id="classify_tools",
        condition=lambda ctx: bool(ctx.source_output.message.tool_calls),
    )
    workflow.add_edge(
        "classify_response",
        "validate_output",
        edge_id="classify_output",
        condition=lambda ctx: not ctx.source_output.message.tool_calls,
    )

    for index, (handler, definition) in enumerate(zip(tools, definitions, strict=True)):
        node_id = f"tool_{index}_{_node_token(definition.name)}"

        def select_calls(
            ctx: Any,
            *,
            selected_name: str = definition.name,
        ) -> list[Mapping[str, Any]]:
            return [
                {"arguments": item.arguments}
                for item in ctx.input.valid_calls
                if item.call.name == selected_name
            ]

        def aggregate_calls(
            ctx: Any,
            *,
            selected_name: str = definition.name,
            selected_id: str = definition.id,
        ) -> ToolExecutionBatch:
            batch = ctx.outputs.latest("validate_tool_calls")
            selected = [
                item
                for item in batch.valid_calls
                if item.call.name == selected_name
            ]
            return ToolExecutionBatch(
                results=tuple(
                    ToolExecutionResult(
                        tool_call_id=item.call.id,
                        tool_id=selected_id,
                        output=output.output,
                        error=output.error,
                    )
                    for item, output in zip(
                        selected,
                        ctx.item_outputs,
                        strict=True,
                    )
                )
            )

        recoverable_handler = recoverable_tool_handler(handler)
        setattr(
            recoverable_handler,
            "__autoagent_runtime_annotations__",
            (
                definition.contract.output.annotation,
                *(
                    parameter.annotation
                    for parameter in definition.contract.input.parameters
                ),
            ),
        )
        workflow.add_node(
            Operator(
                id=definition.id,
                handler=recoverable_handler,
                version=semantic_version,
            ),
            node_id=node_id,
            user_event_mapping=UserEventMapping(
                type="tool_result",
                transform=tool_results,
            ),
        )
        workflow.add_edge(
            "validate_tool_calls",
            node_id,
            edge_id=f"validated_{node_id}",
            condition=(
                lambda ctx, selected_name=definition.name: any(
                    item.call.name == selected_name
                    for item in ctx.source_output.valid_calls
                )
            ),
            policy=EdgePolicy(
                map=MapPolicy(
                    item_selector=select_calls,
                    output_aggregator=aggregate_calls,
                )
            ),
        )
        workflow.add_edge(
            node_id,
            "collect_tool_results",
            edge_id=f"{node_id}_collect",
        )

    workflow.add_edge(
        "validate_tool_calls",
        "collect_tool_results",
        edge_id="invalid_tools_collect",
        condition=lambda ctx: not ctx.source_output.valid_calls,
    )
    workflow.add_edge(
        "collect_tool_results",
        "prepare_conversation",
        edge_id="tools_prepare",
    )
    workflow.add_edge(
        "validate_output",
        "finish",
        edge_id="output_finish",
        condition=lambda ctx: ctx.source_output.valid,
    )
    workflow.add_edge(
        "validate_output",
        "build_output_repair",
        edge_id="output_repair",
        condition=lambda ctx: not ctx.source_output.valid,
    )
    workflow.add_edge(
        "build_output_repair",
        "prepare_conversation",
        edge_id="repair_prepare",
    )
    return workflow


def _internal_operator(
    workflow_id: str,
    name: str,
    version: str,
    handler: Callable[..., Any],
) -> Operator:
    return Operator(
        id=f"{workflow_id}.__react__.{name}",
        handler=handler,
        version=version,
    )


def _semantic_version(value: Any) -> str:
    payload = json.dumps(value, sort_keys=True, separators=(",", ":")).encode()
    return hashlib.sha256(payload).hexdigest()[:16]


def _node_token(value: str) -> str:
    return "".join(character if character.isalnum() else "_" for character in value)
