"""Stable authoring and invocation API for AutoAgent V2."""

from .core.app import AutoAgentApp, InvocationResult, InvocationStream, StreamItem
from .core.compiler import (
    CompileResult,
    Diagnostic,
    WorkflowCompiler,
    WorkflowDefinitionSnapshot,
)
from .core.context import ContextOperation, ContextPatch
from .core.errors import AutoAgentError, RuntimeTransitionError, WorkflowCompileError
from .core.operators import Operator, StreamReducer, ValueContract, Wait
from .core.runtime import RuntimeErrorInfo, RuntimeEvent, UserEvent
from .core.workflow import (
    AggregationContext,
    Backoff,
    Capability,
    ChildInvocationHandle,
    ConditionContext,
    Context,
    Edge,
    ErrorInfo,
    InputMappingContext,
    Map,
    Node,
    OperatorPolicy,
    OutputBindingContext,
    Recovery,
    Retry,
    Stream,
    StreamContext,
    SubWorkflow,
    UserEventMapping,
    Workflow,
    workflow_hook,
)

__all__ = [
    "AggregationContext",
    "AutoAgentApp",
    "AutoAgentError",
    "Backoff",
    "Capability",
    "ChildInvocationHandle",
    "CompileResult",
    "ConditionContext",
    "Context",
    "ContextOperation",
    "ContextPatch",
    "Diagnostic",
    "Edge",
    "ErrorInfo",
    "InputMappingContext",
    "InvocationResult",
    "InvocationStream",
    "StreamItem",
    "Map",
    "Node",
    "Operator",
    "OperatorPolicy",
    "OutputBindingContext",
    "Recovery",
    "Retry",
    "RuntimeErrorInfo",
    "RuntimeEvent",
    "RuntimeTransitionError",
    "Stream",
    "StreamContext",
    "StreamReducer",
    "SubWorkflow",
    "UserEvent",
    "UserEventMapping",
    "ValueContract",
    "Wait",
    "Workflow",
    "WorkflowCompileError",
    "WorkflowCompiler",
    "WorkflowDefinitionSnapshot",
    "workflow_hook",
]
